### ISSUE TITLE
update support to  v56 release, others things (super issue)

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#1386]
(testing checklist is in PR #1388)

So can rein in the version support here a bit, I propose we pear down primary version support on _all_ platforms to:

- [x] v53.05
- [x] v55.01-5bc04d6
- [x] v55.02
- [x] v56.0.2 (release, https://github.com/adcirc/adcirc/releases/tag/v56.0.2)

In the updated v56 patch supported the latest release,

- [x] remove `-FI` (uppercase F uppercase i) flag on Frontera and Lonestar6 causes `src/netcdf_error.F90` to fail compiling/linking on v56-beta-2 (updated in #1387)
- [x] remove `-FI` on the other platforms that use
- [x] remove v55-release from the list
- [x] address #1361 (gfortran)
- [x] address #1383 (change intel-llvm to intel-openapi, add gfortran >= 10)
- [x] #1311 (Intel OpenAPI support on debian)

**Comment by wwlwpd** [comment]
Note, v56 beta 2 is compiling fine on Stampede3

**Comment by wwlwpd** [comment]
FYI @jasonfleming I think the `-FI` issue only comes into play for v 56+. Based on some cursory research, I believe it can be eliminated for any other version without any ill effects.
